name: Build and Deploy Vite App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'  # Adjust the Node.js version to your requirement

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build
        # Add any additional build steps or commands if needed


    

    
      - name: SCP Action
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/GluveFront/dist/

            
      - name: Rollback
        run: |
          ls -al