name: Build and Deploy Vite App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: 의존성 설치
        run: |
          sudo npm install

      - name: React 앱 빌드
        run: |
          sudo npm run build
          ls



  deploy:
      runs-on: ubuntu-latest

      needs: build

      steps:
        - name: Copy files to Lightsail instance
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.LIGHTSAIL_HOST }}
            username: ${{ secrets.LIGHTSAIL_USERNAME }}
            key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
            source: "dist/*"
            target: "/GluveFront/dist"
      

        - name: 롤백
          run: |
           롤백