name: 프론트엔드 배포

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: 의존성 설치
        run: |
          sudo npm install

      - name: React 앱 빌드
        run: |
          sudo npm run build
          ls


      - name: SSH 키 설정
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: 서버로 복사
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              # GluveFront 폴더 확인 후 없으면 생성
              if [ ! -d "/GluveFront/dist" ]; then
                sudo mkdir -p /GluveFront/dist
              fi
            
              # 이전에 연결한 호스트 키를 삭제
              ssh-keygen -R ${{ secrets.SSH_HOST }}
            
              # 빌드된 작업물만 복사
              scp -r dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/GluveFront/dist/
        
        
      - name: React 앱 빌드
        run: |
          롤백