name: Build and Deploy Vite App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust the Node.js version to your requirement

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build
        # Add any additional build steps or commands if needed

  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: SCP Action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/"
          target: "/GluveFront/dist/"

      - name: Rollback
        run: |
          # Add rollback steps or commands here
          # For example, you might want to roll back to a previous deployment

