name: Build and Deploy Vite App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: 의존성 설치
        run: |
          sudo npm install

      - name: React 앱 빌드
        run: |
          sudo npm run build
          ls



  deploy:
      runs-on: ubuntu-latest

      needs: build

      steps:

        - name: 출력
          run: |
           ls -al

        - name: AWS CLI를 사용하여 파일 복사
          run: |
             aws scp -r dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/GluveFront/dist/
      
        - name: 롤백
          run: |
           롤백
