name: 프론트엔드 배포

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: 의존성 설치
        run: |
          sudo npm install

      - name: React 앱 빌드
        run: |
          sudo npm run build
          ls


   

      - name: 서버로 복사
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              # Ensure GluveFront 폴더 exists; create if not
              if [ ! -d "/GluveFront/dist" ]; then
                sudo mkdir -p /GluveFront/dist
              fi
        
              
              # Write SSH_PRIVATE_KEY to a file
              echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
              chmod 600 $HOME/.ssh/id_rsa
        
              # Debug: Print the content of id_rsa for troubleshooting
              cat $HOME/.ssh/id_rsa
        
              # Set correct ownership and permissions for the SSH directory
              chown -R $USER:$USER $HOME/.ssh
              chmod 700 $HOME/.ssh
              chmod 600 $HOME/.ssh/id_rsa
        
              # Copy only the built artifacts
              scp -o StrictHostKeyChecking=no -r dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/GluveFront/dist
        
      - name: React 앱 빌드
        run: |
          롤백